
services:
  drakobuild:
    build: .
    container_name: drakobuild-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'  # Limite de CPUs
          memory: 16G # Limite de memória
